### ISSUE TITLE
作者能出个exe封装的版本吗

### ISSUE THREAD

**Issue by chenlu964** [x1ao4/tmdb-automation#1]
想为爱发电，py不会用，如果能出个exe版本就完美了

**Comment by x1ao4** [comment]
脚本依赖 selenium 实现网页自动化，使用 selenium 需要安装与你的浏览器对应版本的驱动，每个人使用的浏览器版本不同，并且可能随时会更新版本，更新版本就需要更新驱动，所以无法制作一个通用文件适配所有需求。

[README.md](https://github.com/x1ao4/tmdb-automation#readme) 已经给出了具体的运行条件和操作步骤，请根据说明逐步操作，即可使用。

**Comment by chenlu964** [comment]
chromedriver.exe放在谷歌浏览器的安装根目录就行了对把 我现在PY及依赖库都安装好了 也跑起来了 但是还是有错 运行脚本 然后能正确运行 登入账号密码 我的个人主页 然后旧报错了
![QQ截图20231126125112](https://github.com/x1ao4/tmdb-automation/assets/86452332/4a417451-c2b0-484f-9aa6-1e4ec8c524bf)

**Comment by chenlu964** [comment]
只能跑这2步 谷歌浏览器也正常提示受控， 报错后就关闭浏览器界面了
![QQ截图20231126125224](https://github.com/x1ao4/tmdb-automation/assets/86452332/0541fe02-eb70-4afa-a2fb-5376df93f5d5)

**Comment by x1ao4** [comment]
> chromedriver.exe放在谷歌浏览器的安装根目录

你看下这个[教程](https://blog.csdn.net/mingfeng4923/article/details/130989513)。

**Comment by x1ao4** [comment]
> chromedriver.exe放在谷歌浏览器的安装根目录就行了对把 我现在PY及依赖库都安装好了 也跑起来了 但是还是有错 运行脚本 然后能正确运行 登入账号密码 我的个人主页 然后旧报错了 ![QQ截图20231126125112](https://private-user-images.githubusercontent.com/86452332/285629737-4a417451-c2b0-484f-9aa6-1e4ec8c524bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5Nzc2OTksIm5iZiI6MTcwMDk3NzM5OSwicGF0aCI6Ii84NjQ1MjMzMi8yODU2Mjk3MzctNGE0MTc0NTEtYzJiMC00ODRmLTlhYTYtMWU0ZWM4YzUyNGJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI2VDA1NDMxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzZmVlZTdkMDgxZjcxNWI3OWI5NjUyNGZiZWFhODFjNTQxODk0Njc5MzQxN2RkNjBiNWI5OGFmMWE4NDllM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Jrq25XbDmMoJRVFOB74Ff0XxggbzSPPK5w_pjP0wQWM)

Python 默认使用系统的默认编码来读取文件，而在 Windows 上，这个默认编码通常是 gbk。我是在 Mac 测试脚本的，Mac 的文本文档编码 Python 可以直接调用，稍后我会优化一下脚本，解决 Win 的这个编码问题。

**Comment by chenlu964** [comment]
好的 应该就是编码错误 因为已经在跑了 应该是不认编码

**Comment by x1ao4** [comment]
> 好的 应该就是编码错误 因为已经在跑了 应该是不认编码

好的，我已经修改代码了，现在在读写 txt 时指定了使用 utf-8 编码，应该不会报错了，你可以重新下载新版的脚本测试。

**Comment by chenlu964** [comment]
追加剧集的  已经能用了 但是更新剧集的失败了 附上日志
![add_看图王](https://github.com/x1ao4/tmdb-automation/assets/86452332/bcd06631-0927-4aaf-8489-c58522f426e4)
![update](https://github.com/x1ao4/tmdb-automation/assets/86452332/8d6a3241-521b-4e9c-901f-f99aceccd5ad)

**Comment by chenlu964** [comment]
更新剧集数据的脚本 在集页面不动 然后就报错了

**Comment by chenlu964** [comment]
添加和更新剧集都能用了 感谢作者大大。最后希望更新图片也能添加一个win端能用的

**Comment by x1ao4** [comment]
> 最后希望更新图片也能添加一个win端能用的

因为 TMDB 上传图片的界面无法输入图片地址，需要在系统层面进行操作选择图片文件，我常用的是 Mac 所以利用 Mac 系统快捷键实现了选择指定的图片，Windows 无法直接复刻这个方式，需要在 Windows 系统寻找可实现的方法，等我有空研究一下。

如果你有思路也可以提供思路，就是需要一个快捷键调出系统的文件访问系统或者文件查找系统，然后用脚本粘贴要查找的文件地址，打开指定的图片，这样就可以实现了。

**Comment by chenlu964** [comment]
我GPT查了一下 这个库比较符合你说的哦
![QQ截图20231127154630](https://github.com/x1ao4/tmdb-automation/assets/86452332/d67bab12-d7dc-4f60-9b97-8d05d243ef0e)

**Comment by x1ao4** [comment]
> 我GPT查了一下

你如果会用 AI，你可以尝试直接把我的图片脚本整个内容复制下来发给 AI，然后让 AI 给你写一个 Windows 可用的能实现同样功能的脚本，然后你再测试就行了。

这几个 TMDB 脚本都是使用模拟人类操作网页的方式添加内容的，之所以要这样写脚本，就是因为 TMDB 不支持通过 API 向网站添加内容，我想 requests 同样也是不行的。

另外使用 AI 写脚本建议用 Bing/Copilot，我这几个脚本都是用 Bing 写的。

**Comment by chenlu964** [comment]
不太会提问 我提问然后测试下来没用 算了 等大佬你有空再弄吧 超过我这个小白的能力了

**Comment by x1ao4** [comment]
> 最后希望更新图片也能添加一个win端能用的

最新的 [v1.1](https://github.com/x1ao4/tmdb-automation/releases/tag/v1.1) 版本的添加图片功能已经支持在 Windows 上使用了，你可以试一试。
