### ISSUE TITLE
请问是只适配了mac吗？

### ISSUE THREAD

**Issue by 2640yang** [x1ao4/tmdb-automation#2]
请问有打算适配win吗？

**Comment by x1ao4** [comment]
我没有 Windows 设备，部分功能的实现在 Mac 和 Windows 上有差异，除了上传图片的功能，其他功能 Windows 应该是可以正常使用的。上传图片的功能暂时不会考虑适配 Windows。

**Comment by x1ao4** [comment]
最新的 [v1.1](https://github.com/x1ao4/tmdb-automation/releases/tag/v1.1) 版本已经全面支持 Windows 系统了，三个工具都支持在 Windows 上使用了，你可以试一试。
